import { CustomCSVStreamReader, MyCustomRecord } from "./CustomCSVStreamReader";
import { LineByLineReader } from "./LineByLineReader";

/*** Simple Usage ***/

// Providing the file reader and passing it to the CustomCSVStreamReader.
const lineByLineReader = LineByLineReader.createStream('./resources/file.csv');
const customCSVStreamReader = new CustomCSVStreamReader(lineByLineReader);

// Reading the data;
let record: MyCustomRecord | false; // This is the custom type of our object generated by the programmer
while (record = customCSVStreamReader.next()) {
  console.log(record);
}

/*
output: 
{ grade: 1, playerId: 'BYCYR', score: 19923 }
{ grade: 2, playerId: '6T42O', score: 19880 }
{ grade: 3, playerId: '3NKuC', score: 19840 }
{ grade: 4, playerId: 'tY0M0', score: 19835 }
{ grade: 5, playerId: '0RMgu', score: 19823 }
{ grade: 6, playerId: '0LssH', score: 19813 }
...
*/